import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline';
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

const project = resolve(import.meta.dirname, '../..');
const fixture = spawn(resolve(project, '.venv/bin/python'), ['-B', '-m', 'tests.dashboard_browser_fixture'], { cwd: project, stdio: ['ignore', 'pipe', 'inherit'] });
let browser;
try {
  const config = await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('Fixture startup timed out')), 15000);
    createInterface({ input: fixture.stdout }).once('line', line => { clearTimeout(timer); resolve(JSON.parse(line)); });
    fixture.once('exit', code => { clearTimeout(timer); reject(new Error(`Fixture exited: ${code}`)); });
  });
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await page.addInitScript(() => {
    window.canvasText = [];
    const original = CanvasRenderingContext2D.prototype.fillText;
    CanvasRenderingContext2D.prototype.fillText = function(text, ...args) { window.canvasText.push({ text, font: this.font }); return original.call(this, text, ...args); };
  });
  const failures = [], external = [];
  await page.route('**/api/dashboard/explain/status', route => route.fulfill({ json: { available: false, models: [], default: null, error: 'Ollama is not running. Start it and try again.' } }));
  page.on('pageerror', error => failures.push(error.message));
  page.on('request', request => { if (!request.url().startsWith(config.url) && !request.url().startsWith(config.empty_url) && !request.url().startsWith('blob:')) external.push(request.url()); });
  mkdirSync(resolve(project, 'reports/local/dashboard-checks'), { recursive: true });
  const screenshot = name => page.screenshot({ path: resolve(project, `reports/local/dashboard-checks/${name}.png`), fullPage: true });

  await page.goto(config.url);
  await expect(page.locator('nav a[aria-current="page"]')).toHaveText('Map');
  await expect(page.locator('.headline')).toHaveText('90.9%');
  await page.getByRole('link', { name: 'Risk', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Files with gaps' })).toBeVisible();
  await expect(page.locator('nav a[aria-current="page"]')).toHaveText('Risk');
  await expect(page.locator('.risk-table tbody tr')).toHaveCount(2);
  await expect(page.locator('.risk-table tbody tr').first()).toContainText('a.py');
  expect(await page.locator('.missing-lines').allTextContents()).toEqual(['18', '12']);
  expect(await page.evaluate(() => getComputedStyle(document.body).backgroundColor)).toBe('rgb(0, 0, 0)');
  await screenshot('risk');
  await page.getByRole('button', { name: 'a.py ./', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').locator('.source-line')).toHaveCount(21);
  await expect(page.getByRole('dialog')).toContainText('3 of 21 lines seen.');
  await expect(page.getByRole('dialog').locator('.detail-state')).toContainText('Partly seen · 14.2%');
  await expect(page.getByRole('dialog').locator('.source-line.untested')).toHaveCount(21);
  await expect(page.getByRole('link', { name: 'Study unseen code' })).toBeVisible();
  await page.getByText('More evidence', { exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('on screen for at least a second');
  await page.getByText('Unseen sections · 1', { exact: true }).click();
  await expect(page.locator('.section-links a')).toHaveCount(1);
  await screenshot('file-detail');
  await page.getByRole('link', { name: 'Full guide', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'a.py' })).toBeVisible();
  await expect(page.locator('.guide-item')).toHaveCount(1);
  await page.getByRole('button', { name: 'Show code' }).click();
  await expect(page.locator('.guide-code .source-line').first()).toContainText('LIMIT = 10');
  await page.getByRole('button', { name: 'Whole file' }).click();
  await expect(page.locator('.guide-outline li')).toHaveCount(1);
  await expect(page.locator('.local-model')).toContainText('The guide works without it');
  await expect(page.getByRole('button', { name: 'Explain', exact: true })).toHaveCount(0);
  const status = { available: true, endpoint: 'http://127.0.0.1:11434', models: ['qwen2.5-coder:7b', 'llama3:8b'], default: 'qwen2.5-coder:7b', error: null };
  let explainReply = { status: 200, body: { text: '- Sets the limit (L1).', model: 'qwen2.5-coder:7b', scope: 'unit', cached: false } };
  const explainBodies = [];
  await page.route('**/api/dashboard/explain/status', route => route.fulfill({ json: status }));
  await page.route('**/api/dashboard/explain', route => { explainBodies.push(route.request().postDataJSON()); return route.fulfill({ status: explainReply.status, json: explainReply.body }); });
  await page.reload();
  await expect(page.getByLabel('Local model')).toHaveValue('qwen2.5-coder:7b');
  await page.getByRole('button', { name: 'Explain', exact: true }).click();
  await expect(page.locator('.guide-explain-text')).toHaveText('- Sets the limit (L1).');
  await expect(page.locator('.guide-explain .eyebrow')).toContainText('Generated by qwen2.5-coder:7b on this machine');
  expect(explainBodies[0]).toMatchObject({ path: 'a.py', start: 1, end: 20, model: 'qwen2.5-coder:7b', regenerate: false });
  explainReply = { status: 502, body: { error: 'Ollama is not running. Start it and try again.' } };
  await page.getByRole('button', { name: 'Regenerate' }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Ollama is not running' })).toBeVisible();
  explainReply = { status: 200, body: { text: 'Whole file.', model: 'qwen2.5-coder:7b', scope: 'file', cached: true } };
  await page.getByRole('button', { name: 'Summarize this file' }).click();
  await expect(page.getByText('Whole file.')).toBeVisible();
  expect(explainBodies.at(-1).start).toBeUndefined();
  await expect(page.getByRole('button', { name: /Take quiz · 3 questions/ })).toBeVisible();
  let importReply = { status: 409, body: { error: 'Question 1 needs correct_index from 0 to 3.' } };
  const quizBodies = [];
  await page.route('**/api/dashboard/quiz/prompt', route => { quizBodies.push(route.request().postDataJSON()); return route.fulfill({ json: { prompt: 'WRITE A QUIZ', start: 1, end: 20, question_count: 3, note: '' } }); });
  await page.route('**/api/dashboard/quiz/import', route => { quizBodies.push(route.request().postDataJSON()); return route.fulfill({ status: importReply.status, json: importReply.body }); });
  await page.getByRole('button', { name: 'Make another quiz' }).click();
  await expect(page.getByLabel('Prompt')).toHaveValue('WRITE A QUIZ');
  await expect(page.getByRole('button', { name: 'Create quiz' })).toBeDisabled();
  await page.getByLabel('Model reply').fill('{"questions": []}');
  await page.getByRole('button', { name: 'Create quiz' }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'correct_index' })).toBeVisible();
  importReply = { status: 200, body: { set_id: 'abc', duplicate: false, question_count: 3, warnings: ['Question 2 mentions `x`, which does not appear in this code.'], key_quality: 'Answer keys come from the model that wrote the quiz and are not verified.' } };
  await page.getByRole('button', { name: 'Create quiz' }).click();
  await expect(page.getByText('Quiz ready.')).toBeVisible();
  await expect(page.getByText('does not appear in this code')).toBeVisible();
  expect(quizBodies.at(-1)).toMatchObject({ path: 'a.py', start: 1, end: 20, reply: '{"questions": []}' });
  await page.unroute('**/api/dashboard/quiz/prompt'); await page.unroute('**/api/dashboard/quiz/import');
  await page.unroute('**/api/dashboard/explain'); await page.unroute('**/api/dashboard/explain/status');
  await page.reload();
  await screenshot('guide');
  await page.getByRole('link', { name: 'Back to Risk' }).click();
  await expect(page.getByRole('heading', { name: 'Files with gaps' })).toBeVisible();
  await page.locator('.file-link').filter({ hasText: 'a.py' }).click();
  await page.getByRole('button', { name: 'Take quiz', exact: true }).click();
  await expect(page.locator('.question-panel h1')).toHaveText('Question 0: first');
  await expect(page.locator('.state-chip, .app-header, .connection-strip, .headline, .risk-table')).toHaveCount(0);
  await expect(page.locator('[class*="state-"]')).toHaveCount(0);
  await expect(page.locator('.review-source .source-line')).toHaveCount(20);
  const answerRequests = [];
  page.on('request', request => { if (request.url().endsWith('/review/answer')) answerRequests.push(request.postDataJSON()); });
  await screenshot('review');
  for (let i = 0; i < 3; i++) {
    await page.locator('.options button').nth(i).click();
    await page.getByRole('button', { name: 'Solid', exact: true }).click();
    if (i < 2) await expect(page.locator('.question-panel h1')).toHaveText(`Question ${i+1}: first`);
  }
  await expect(page.getByRole('heading', { name: 'Quiz results' })).toBeVisible();
  expect(answerRequests).toHaveLength(3);
  for (const body of answerRequests) expect(Object.keys(body).sort()).toEqual(['attempt_id', 'chosen_index', 'confidence', 'question_id']);
  const reports = [];
  await page.route('**/api/dashboard/review/report', route => { reports.push(route.request().postDataJSON()); return route.fulfill({ json: { status: 'rejected' } }); });
  await page.getByRole('button', { name: 'This answer key looks wrong' }).first().click();
  await expect(page.getByText('Remove this whole quiz?')).toBeVisible();
  await page.getByRole('button', { name: 'Keep it' }).click();
  expect(reports).toHaveLength(0);
  await page.getByRole('button', { name: 'This answer key looks wrong' }).first().click();
  await page.getByRole('button', { name: 'Remove quiz' }).click();
  await expect(page.getByText('Quiz removed.')).toBeVisible();
  expect(reports[0]).toMatchObject({ question_id: 'q1' });
  await page.unroute('**/api/dashboard/review/report');
  await page.getByRole('link', { name: 'Return to review queue' }).click();
  await expect(page.locator('.risk-table tbody tr').first()).toContainText('b.py');
  await expect(page.locator('.risk-table tbody tr').last()).toContainText('Sample passed');
  await expect(page.locator('.risk-table tbody tr').last().locator('.untested')).toHaveCount(0);
  await page.getByRole('link', { name: 'Map', exact: true }).click();
  await expect(page.locator('.map-cell')).toHaveCount(2);
  await expect(page.locator('.map-cell.untested')).toHaveCount(1);
  await expect(page.locator('.headline')).toHaveText('90.9%');
  await expect(page.getByText('30 lines never on screen, across 2 files')).toBeVisible();
  expect(await page.locator('.headline').evaluate(el => getComputedStyle(el).fontFamily)).toContain('IBM Plex Mono');
  await screenshot('map');
  await page.getByRole('link', { name: 'Timeline', exact: true }).click();
  await expect(page.locator('.weekly-chart')).toBeVisible();
  await expect(page.locator('.lane')).toHaveCount(1);
  expect(await page.locator('.weekly-bar').evaluate(el => el.getBoundingClientRect().width)).toBe(36);
  await expect(page.getByText('Busiest week: 1 file.')).toBeVisible();
  await screenshot('timeline');
  await page.getByRole('link', { name: 'Insights', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Confidently wrong' })).toBeVisible();
  await expect(page.locator('.calibration').last()).toContainText('3 / 3 answers correct');
  await screenshot('insights');
  await page.getByRole('link', { name: 'Share', exact: true }).click();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download PNG' }).click();
  await (await download).saveAs(resolve(project, 'reports/local/dashboard-checks/share.png'));
  expect(await page.locator('canvas').evaluate(c => [c.width, c.height])).toEqual([1200, 630]);
  expect(await page.evaluate(() => window.canvasText.find(t => t.text === '90.9%')?.font)).toContain('IBM Plex Mono');
  expect(await page.evaluate(() => window.canvasText.some(t => /reading|understanding|eligible|current source/i.test(t.text)))).toBe(false);
  await page.goto(`${config.empty_url}/#risk`);
  await expect(page.getByText('No recording yet.', { exact: true })).toBeVisible();
  await screenshot('empty');
  await page.getByRole('link', { name: 'Map', exact: true }).click();
  await expect(page.locator('.headline')).toHaveText('Start recording');
  await page.getByRole('link', { name: 'Insights', exact: true }).click();
  await expect(page.getByText('No quizzes taken yet.', { exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Review a file', exact: true })).toBeVisible();
  await expect(page.locator('.chart-panel, .big-stat')).toHaveCount(0);
  await page.getByRole('button', { name: 'How this is measured', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('does not establish that it was read or understood');
  await expect(page.getByText(/does not establish that it was read or understood/)).toHaveCount(1);
  await page.getByRole('button', { name: 'Close methodology' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  for (const view of ['Risk', 'Learning', 'Map', 'Timeline', 'Insights', 'Share']) {
    await page.getByRole('link', { name: view, exact: true }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
    expect(await page.locator('body').innerText()).not.toMatch(/eligible|current source|observer|binding|collector|stored|\brecord\b/i);
    await expect(page.getByRole('button', { name: 'How this is measured', exact: true })).toBeVisible();
  }
  await page.goto(config.url + '#guide?path=a.py');
  await expect(page.locator('.guide-item')).toHaveCount(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.getByRole('link', { name: 'Learning', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Code to revisit' })).toBeVisible();
  await expect(page.locator('.learning-file')).toHaveCount(2);
  await screenshot('learning');
  await page.locator('.learning-file').filter({ has: page.getByRole('heading', { name: 'a.py', exact: true }) }).getByRole('link', { name: 'Open lesson', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Inspect this section' })).toBeVisible();
  expect(await page.locator('.lesson-panel .source-line').count()).toBeGreaterThan(0);
  await expect(page.getByRole('button', { name: 'Previous unit' })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Next unit' })).toBeDisabled();
  await page.route('**/api/dashboard/explain/status', route => route.fulfill({ json: { available: false, models: [], default: null, error: 'Ollama is not running. Start it and try again.' } }));
  await page.reload();
  await page.getByRole('tab', { name: 'Explanation', exact: true }).click();
  await expect(page.locator('.lesson-panel')).toContainText('Ollama is not running');
  await page.getByRole('button', { name: 'Inspect the code', exact: true }).click();
  await expect(page.getByRole('tab', { name: 'Code', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.getByRole('tab', { name: 'Code', exact: true }).focus();
  await page.keyboard.press('End');
  await expect(page.getByRole('tab', { name: 'Quiz', exact: true })).toBeFocused();
  await page.getByRole('button', { name: /Make (a|another) quiz/ }).click();
  await page.getByLabel('Model reply').fill('Raw reply to preserve while inspecting code');
  await page.getByRole('tab', { name: 'Code', exact: true }).click();
  await expect(page.getByLabel('Model reply')).toBeHidden();
  await page.getByRole('tab', { name: 'Quiz', exact: true }).click();
  await expect(page.getByLabel('Model reply')).toHaveValue('Raw reply to preserve while inspecting code');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await screenshot('learning-lesson');
  // Exercise the empty-column and zero-gap branches with fixture responses.
  let scenario = 'changed';
  await page.route('**/api/dashboard', async route => {
    const response = await route.fetch();
    const data = await response.json();
    if (scenario === 'changed') {
      data.files = data.files.map(f => f.path === 'a.py' ? { ...f, changed_unseen_lines: 1, changed_unseen_ranges: [[10, 10]] } : f);
    } else if (scenario === 'unknown') {
      data.files = data.files.map(f => ({ ...f, current_uncertain: true, state: 'uncertain', commits_90d: null }));
    } else if (scenario === 'zero') {
      data.has_observations = true;
      data.files = data.files.map(f => ({ ...f, current_uncertain: false, unknown_lines: 0, reported_lines: f.line_count, state: 'reported' }));
      data.totals.reported_lines = data.totals.line_count;
    } else data.files = [];
    await route.fulfill({ response, json: data });
  });
  await page.goto(`${config.url}/?scenario=changed#risk`);
  await expect(page.getByText('1 changed line unseen', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'a.py ./', exact: true }).click();
  await expect(page.getByRole('dialog').locator('.source-line.changed-unseen')).toHaveCount(1);
  await page.getByRole('button', { name: 'Show changed lines', exact: true }).click();
  await expect(page.getByRole('dialog').locator('.source-line.jump')).toHaveAttribute('data-line', '10');
  scenario = 'unknown';
  await page.goto(`${config.empty_url}/#risk`);
  await expect(page.locator('.risk-table tbody tr')).toHaveCount(2);
  await expect(page.getByRole('columnheader', { name: 'Missing lines', exact: true })).toHaveCount(0);
  await expect(page.getByRole('columnheader', { name: 'Commits', exact: true })).toHaveCount(0);
  scenario = 'zero';
  await page.goto(`${config.empty_url}/?scenario=zero#map`);
  await expect(page.locator('.headline')).toHaveText('0%');
  await page.getByRole('link', { name: 'Learning', exact: true }).click();
  await expect(page.getByText('No gaps recorded.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'All files', exact: true }).click();
  await expect(page.locator('.learning-file')).toHaveCount(2);
  scenario = 'empty';
  await page.goto(`${config.empty_url}/?scenario=empty#share`);
  await expect(page.getByText('No files to share.', { exact: true })).toBeVisible();
  await expect(page.locator('canvas')).toHaveCount(0);
  await page.getByRole('link', { name: 'Learning', exact: true }).click();
  await expect(page.getByText('No files to study.', { exact: true })).toBeVisible();
  await expect(page.locator('.learning-file')).toHaveCount(0);
  expect(external).toEqual([]);
  expect(failures).toEqual([]);
  console.log('Browser checks passed: Learning hub, lesson tabs, keyboard navigation, quiz draft preservation, model fallback, Risk, source, review, Map, Timeline, Insights, PNG, empty states, mobile, and local-only requests.');
} finally {
  if (browser) await browser.close();
  fixture.kill('SIGTERM');
}
